openapi: 3.0.3
info:
  title: Intention Service API
  description: API cho dịch vụ quản lý yêu cầu đặt xe
  version: 1.0.0
  contact:
    name: Nhóm 4
    email: nhom4@example.com
servers:
  - url: http://localhost:8800
    description: API Gateway URL
  - url: http://localhost:8001
    description: Intention Service URL trực tiếp

tags:
  - name: intentions
    description: Các API liên quan đến yêu cầu đặt xe

paths:
  /api/intentions/place:
    post:
      tags:
        - intentions
      summary: Tạo yêu cầu đặt xe mới
      description: Tạo một yêu cầu đặt xe mới từ khách hàng
      operationId: placeIntention
      requestBody:
        description: Thông tin yêu cầu đặt xe
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyIntention'
        required: true
      responses:
        '200':
          description: Yêu cầu đặt xe được tạo thành công
          content:
            text/plain:
              schema:
                type: string
                example: "user 1 place intention successfully with start longitude: 105.8521 and start latitude: 21.0245 and dest longitude: 105.8315 and dest latitude: 21.0277"
        '400':
          description: Dữ liệu đầu vào không hợp lệ
        '500':
          description: Lỗi Server

  /api/intentions/confirm:
    post:
      tags:
        - intentions
      summary: Xác nhận yêu cầu đặt xe
      description: Tài xế xác nhận chấp nhận yêu cầu đặt xe
      operationId: confirmIntention
      parameters:
        - name: driverId
          in: query
          description: ID của tài xế
          required: true
          schema:
            type: integer
            format: int32
        - name: intentionId
          in: query
          description: ID của yêu cầu đặt xe
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Kết quả xác nhận
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          description: Dữ liệu đầu vào không hợp lệ
        '500':
          description: Lỗi Server

  /api/intentions/all:
    get:
      tags:
        - intentions
      summary: Lấy tất cả yêu cầu đặt xe
      description: Trả về danh sách tất cả yêu cầu đặt xe trong hệ thống
      operationId: getAllIntentions
      responses:
        '200':
          description: Danh sách yêu cầu đặt xe
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Intention'
        '500':
          description: Lỗi Server

  /api/intentions/{id}:
    get:
      tags:
        - intentions
      summary: Lấy thông tin yêu cầu đặt xe theo ID
      description: Trả về thông tin chi tiết của một yêu cầu đặt xe dựa trên ID
      operationId: getIntentionById
      parameters:
        - name: id
          in: path
          description: ID của yêu cầu đặt xe
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Thông tin yêu cầu đặt xe
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Intention'
        '404':
          description: Không tìm thấy yêu cầu đặt xe
        '500':
          description: Lỗi Server

components:
  schemas:
    MyIntention:
      type: object
      required:
        - userId
        - startLongitude
        - startLatitude
        - destLongitude
        - destLatitude
      properties:
        userId:
          type: integer
          format: int32
          example: 1
        startLongitude:
          type: number
          format: double
          example: 105.8521
        startLatitude:
          type: number
          format: double
          example: 21.0245
        destLongitude:
          type: number
          format: double
          example: 105.8315
        destLatitude:
          type: number
          format: double
          example: 21.0277

    Customer:
      type: object
      properties:
        customerId:
          type: integer
          format: int32
          example: 1
        customerName:
          type: string
          example: "Nguyễn Văn A"
        customerMobile:
          type: string
          example: "0987654321"
        userType:
          type: string
          example: "Customer"

    DriverVo:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 11
        userName:
          type: string
          example: "Driver 1"
        mobile:
          type: string
          example: "0912345671"
        type:
          type: string
          example: "Driver"

    Candidate:
      type: object
      properties:
        cid:
          type: integer
          format: int32
          example: 1
        driverId:
          type: integer
          format: int32
          example: 11
        driverName:
          type: string
          example: "Driver 1"
        driverMobile:
          type: string
          example: "0912345671"
        longitude:
          type: number
          format: double
          example: 105.8315
        latitude:
          type: number
          format: double
          example: 21.0277
        created:
          type: string
          format: date-time
          example: "2024-05-20T10:30:45"

    Intention:
      type: object
      properties:
        mid:
          type: integer
          format: int32
          example: 1
        startLongitude:
          type: number
          format: double
          example: 105.8521
        startLatitude:
          type: number
          format: double
          example: 21.0245
        destLongitude:
          type: number
          format: double
          example: 105.8315
        destLatitude:
          type: number
          format: double
          example: 21.0277
        customer:
          $ref: '#/components/schemas/Customer'
        status:
          type: string
          enum: [Inited, Unconfirmed, Confirmed, Failed]
          example: "Unconfirmed"
        selectedDriver:
          $ref: '#/components/schemas/DriverVo'
        updated:
          type: string
          format: date-time
          example: "2024-05-20T10:30:45"
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/Candidate'