# gateway/src/main/resources/application.yml
spring:
  cloud:
    gateway:
      routes:
        - id: uc-service
          uri: lb://UC-SERVICE
          predicates:
            - Path=/api/users/**
        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/api/position/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
        - id: intention-service
          uri: lb://INTENTION-SERVICE
          predicates:
            - Path=/api/intentions/**