# gateway/src/main/resources/application.yml

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: uc-service
          uri: lb://UC-SERVICE
          predicates:
            - Path=/users/**
        - id: position-service
          uri: lb://POSITION-SERVICE
          predicates:
            - Path=/api/position/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
        - id: intention-service
          uri: lb://INTENTION-SERVICE
          predicates:
            - Path=/api/intentions/**

server:
  port: 8800

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
