server:
  port: 8001
spring:
  application:
    name: intention-service
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/qbike?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    tomcat:
      max-active: 10
      min-idle: 3
  data:
    redis:
      host: redis
      timeout: 2000ms
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: 1000ms
          max-idle: 8
          min-idle: 0
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1.0f
logging:
  level:
    root: INFO
    org.hibernate: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true